/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quside_QusideQRNG */

#ifndef _Included_com_quside_QusideQRNG
#define _Included_com_quside_QusideQRNG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quside_QusideQRNG
 * Method:    findBoards
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_quside_QusideQRNG_findBoards
  (JNIEnv *, jobject);

/*
 * Class:     com_quside_QusideQRNG
 * Method:    getRandom
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_com_quside_QusideQRNG_getRandom
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_quside_QusideQRNG
 * Method:    getBoards
 * Signature: ([[S[S)V
 */
JNIEXPORT void JNICALL Java_com_quside_QusideQRNG_getBoards
  (JNIEnv *, jobject, jobjectArray, jshortArray);

/*
 * Class:     com_quside_QusideQRNG
 * Method:    findDevice
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_quside_QusideQRNG_findDevice
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_quside_QusideQRNG
 * Method:    qualityQFactor
 * Signature: (I[F)I
 */
JNIEXPORT jint JNICALL Java_com_quside_QusideQRNG_qualityQFactor
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     com_quside_QusideQRNG
 * Method:    getHmin
 * Signature: (I[F)I
 */
JNIEXPORT jint JNICALL Java_com_quside_QusideQRNG_getHmin
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     com_quside_QusideQRNG
 * Method:    getCalibrationStatus
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_quside_QusideQRNG_getCalibrationStatus
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_quside_QusideQRNG
 * Method:    setCalibration
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_quside_QusideQRNG_setCalibration
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
